
  name: DevSecOps
  
  on:
    push:
      branches:
        - main
    pull_request:
  
  permissions:
    contents: read
  
  jobs:
    
    # -------------------------
    # SAST
    # -------------------------
    sast:
      name: SAST Semgrep
      runs-on: ubuntu-latest
      
      container:
        image: semgrep/semgrep:latest
      
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Prepare reports directory
          run: mkdir -p reports

        - name: Run Semgrep
          continue-on-error: true
          run: |
            semgrep scan \
              --config semgrep-rules.yml \
              --sarif \
              --output reports/semgrep-report.sarif .

        - name: Upload Semgrep report
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: semgrep-report
            path: reports/semgrep-report.sarif
            retention-days: 7
    
    # -------------------------
    # SCA
    # -------------------------
    sca:
      name: OWASP Dependency-Check
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Java
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: "21"

        - name: Run Dependency-Check
          uses: dependency-check/Dependency-Check_Action@main
          with:
            project: OsaCrud
            path: "."
            format: "ALL"

        - name: Upload Dependency-Check reports
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: dependency-check-report
            path: reports/
            retention-days: 7
    
    # -------------------------
    # DAST
    # -------------------------
    dast:
      name: DAST OWASP ZAP
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Build and start application
          run: docker compose up -d --build

        - name: Wait for API
          run: |
            echo "Waiting for API..."
            
            for i in $(seq 1 40); do
              if curl -fsS http://localhost:8080/swagger/v1/swagger.json > /dev/null; then
                echo "API is ready"
                exit 0
              fi
            
              sleep 3
            done
            
            docker compose logs
            exit 1

        - name: Run ZAP API Scan
          uses: zaproxy/action-api-scan@v0.9.0
          with:
            target: "http://localhost:8080/swagger/v1/swagger.json"
            format: openapi
            rules_file_name: zap-rules.tsv
            fail_action: false

        - name: Shutdown stack
          if: always()
          run: docker compose down -v
