name: OWASP Dependency-Check SCA

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    container:
      image: owasp/dependency-check:latest
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Prepare folders
        run: |
          mkdir -p dependency-check-report
          mkdir -p .dependency-check

      - name: Run Dependency-Check
        continue-on-error: true
        run: |
          /usr/share/dependency-check/bin/dependency-check.sh \
            --data .dependency-check \
            --scan . \
            --format HTML \
            --format JSON \
            --project dotnet-api \
            --failOnCVSS 11 \
            --out dependency-check-report \
            --noupdate

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report/