name: OWASP Dependency-Check SCA

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Cache OWASP DB
        uses: actions/cache@v4
        with:
          path: ~/.dependency-check
          key: dependency-check-db

      - name: Download Dependency-Check
        run: |
          wget https://github.com/dependency-check/DependencyCheck/releases/download/v12.2.2/dependency-check-12.2.2-release.zip
          unzip dependency-check-12.2.2-release.zip

      - name: Run scan
        continue-on-error: true
        run: |
          mkdir -p reports

          dependency-check/bin/dependency-check.sh \
            --scan . \
            --format ALL \
            --project dotnet-api \
            --out reports \
            --disableNvd \
            --failOnCVSS 11

      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/